language: php
php:
 - 5.3
 - 5.4
 - 5.5

branches:
  - master

matrix:
  include:
    - php: 5.3
      env: VARIA=true
      before_script:
       - git clone https://github.com/Elgg/Elgg.git ../Elgg && cd ../Elgg
       - git checkout 1.9
       - mv ../hypeGallery mod/hypeGallery
       - node -v
       - pear install pear/PHP_CodeSniffer
       - mkdir ../elgg-coding-standards
       - git clone https://github.com/Elgg/elgg-coding-standards.git ../elgg-coding-standards/
       - phpenv rehash
       - curl -sS https://getcomposer.org/installer | php
       - wget https://scrutinizer-ci.com/ocular.phar
      script:
       - phpcs --standard=../elgg-coding-standards/elgg.xml --warning-severity=0 --ignore=*../Elgg/mod/hypeGallery/tests/*,*./Elgg/mod/hypeGallery/vendors/* ../Elgg/mod/hypeGallery/
       - phpunit --coverage-clover=coverage.clover
       - php composer.phar validate --verbose ../Elgg/mod/hypeGallery/composer.json
      after_script:
       - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

services:
 - mysql

before_script:
 - git clone https://github.com/Elgg/Elgg.git ../Elgg && cd ../Elgg
 - git checkout 1.9
 - mv ../hypeGallery mod/hypeGallery
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f ../Elgg/install/cli/travis_installer.php
 - php -f ../Elgg/mod/hypeGallery/.travis/activate.php

script:
 - phpunit
 - php -f ../Elgg/engine/tests/suite.php

notifications:
  email: false